// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu81Y2qzfFUMcQfmuTU8Qd0SWRoDGGRiI',
    appId: '1:1062313333608:web:af19d32501f9f452033cdd',
    messagingSenderId: '1062313333608',
    projectId: 'characrea-110c3',
    authDomain: 'characrea-110c3.firebaseapp.com',
    storageBucket: 'characrea-110c3.appspot.com',
    measurementId: 'G-XLSZJJ8HKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe4jQWHzlvc9ccY9_593X1RmU2rzNxqyw',
    appId: '1:1062313333608:android:3f448a002b5f4ac9033cdd',
    messagingSenderId: '1062313333608',
    projectId: 'characrea-110c3',
    storageBucket: 'characrea-110c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwe7ej1hXUuXOHEf8WKZ25m9zB_thI7H8',
    appId: '1:1062313333608:ios:371b04b9e65c19c0033cdd',
    messagingSenderId: '1062313333608',
    projectId: 'characrea-110c3',
    storageBucket: 'characrea-110c3.appspot.com',
    iosClientId: '1062313333608-326tiec82ve00mgfg1p4hp9pd2s0d2b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.characrea',
  );
}
